#!/usr/bin/env python3
import argparse
import json
import subprocess
import sys
from pathlib import Path


PAGES_REPO = "termux-user-repository/pypi"
PAGES_EVENT_TYPE = "from_wheel"


def run_cmd(args: list[str], *, input_text: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(args, check=True, text=True, input=input_text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Dispatch aggregated wheel manifest records to pages repository")
    parser.add_argument("manifest_files", nargs="*", help="JSONL manifest files generated by build jobs")
    return parser.parse_args()


def row_key(row: dict[str, str]) -> tuple[str, str, str]:
    return row["repo"], row["tag"], row["filename"]


def load_records(files: list[str]) -> list[dict[str, str]]:
    merged: dict[tuple[str, str, str], dict[str, str]] = {}
    for file_name in files:
        file_path = Path(file_name)
        if not file_path.exists():
            continue
        with file_path.open("r", encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                key = row_key(row)
                merged[key] = row

    rows = sorted(
        merged.values(),
        key=lambda x: (x.get("normalized_name", ""), x.get("version", ""), x.get("filename", "")),
    )
    return rows


def dispatch(records: list[dict[str, str]]) -> None:
    payload = {
        "event_type": PAGES_EVENT_TYPE,
        "client_payload": {
            "source": "pypi-wheel-builder-trigger",
            "wheels": records,
        },
    }
    run_cmd(
        ["gh", "api", f"repos/{PAGES_REPO}/dispatches", "--method", "POST", "--input", "-"],
        input_text=json.dumps(payload),
    )


def main() -> int:
    args = parse_args()
    records = load_records(args.manifest_files)
    if not records:
        print("No manifest records found, skip dispatch")
        return 0

    dispatch(records)
    print(f"Dispatched {len(records)} manifest records to {PAGES_REPO}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(1)
